version: '3.8'

services:
  postgres:
    container_name: pg_sql
    image: postgres
    environment:
      POSTGRES_DB: sportOnDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
#      PGDATA: /var/lib/postgresql/data
#      PGDATA: /data/postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#      - D:\sport-on-data:/var/lib/postgresql/data
#      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: always

  sporton:
    container_name: sport_on_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8084:8089
    depends_on:
      - postgres

volumes:
  postgres_data: