version: '3.8'

services:
  postgres:
    container_name: pg_sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sportOnDB
      PGDATA: /data/postgres
    ports:
      - 5434:5432
    volumes:
      - postgres:/var/lib/postgresql/data
#      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: unless-stopped

  sporton:
    container_name: sport_on_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8084:8089
    depends_on:
      - postgres

volumes:
  postgres: