services:
  postgres:
    container_name: pg_sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sportOnDB
      POSTGRES_DATA: /data/postgres
    ports:
      - 5434:5432
    volumes:
      - sporton_db:/var/lib/postgresql/data
    restart: unless-stopped

  sporton:
    container_name: sport_on_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8084:8089
    depends_on:
      - postgres

volumes:
  sporton_db:
    driver: local